# Dependencies
markdown:         redcarpet
highlighter:      pygments
gem:              [jekyll-paginate, jekyll-gists]

# Permalinks
permalink:        pretty

# Setup
title:            Lalitha Weds Ajay
tagline:          'Together is a beautiful place to be.'
url:              https://www.lalithawedsajay.com
baseurl:          /

author:
  name:           'Ajay Kavuri'
  url:            https://pseudoaj.com

paginate:         5

# Custom vars
version:          1.0.0

